### ISSUE TITLE
Does the Model works without GroundTruth Causal Graph ?

### ISSUE THREAD

**Issue by SaqibMamoon** [larslorch/avici#2]
Dear Authors, 

Thanks for sharing the code and such a marvelous article, I am trying to understand the code and the work. However, I am not sure whether this approach work without the causal graph g[d,d] ? Please provide the guidance.

Thanks in advance.

**Comment by larslorch** [comment]
Thanks for reaching out. Could you be more specific with your question? 
Training the model does not work without knowing the graphs. The synthetic data-generating process used for training has to generate both causal graphs G and the corresponding datasets D, and the model is trained to predict the (posterior approximation of) G given D. At test-time, the model only requires a dataset D to make a prediction.
