### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by rmwu** [larslorch/avici#3]
Hi! Two notes regarding installation (would be nice to include in README):

It appears that the PyPI package is out of date, as ```sklearn``` support has been deprecated.

There are two solutions (in addition to updating the binaries on PyPI):
- Remove the ```sklearn``` line in ```setup.py``` and installing via ```pip install -e .```
- ```export SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True```

Also, ```cmake``` seems to be required for building some of the dependencies, notably ```pyarrow```. ~~Is there a Python/system requirement for building this?~~

**Edit**: It appears that ```python=3.10``` is required. Newer versions won't work.

**Comment by larslorch** [comment]
Hi! Thanks for the pointers. The requirements issue and PyPI package should be fixed now, the example [colab notebook](https://colab.research.google.com/github/larslorch/avici/blob/master/example-pretrained/example.ipynb) works. It is possible that `pyarrow` requires Python 3.10, I added this to the requirements. Please let me know if you encounter further issues!
